### ISSUE TITLE
Does not works with last version of Unity (5.0.x)

### ISSUE THREAD

**Issue by istagir** [devtrends/Unity.WebAPI#13]
I've get an error, when I try to compile my prject: 

```
Error	CS0246	The type or namespace name 'UnityContainer' could not be found (are you missing a using directive or an assembly reference?)
```

**Comment by apaolitto** [comment]
Same for me. I tried to take the same classes into my project with Unity 5.0 but then I get the error : "The current type, System.Web.Http.Hosting.IHostBufferPolicySelector, is an interface and cannot be constructed". I'm pretty much to the point to revert to Unity 4.

**Comment by leung85** [comment]
@istagir  @apaolitto  The same error.   
And my solution is Install a package "Unity.Container"  which also provided by Microsoft.Practices.Unity.

And then git clone this Unity.WebAPI Project and update all Nuget package, since Unity.WebAPI still reference  Unity 4.X, if you use Unity 5.0 may have reference error.

After that, it should work again.

@devtrends Would you please update the package to support Unity 5.0. Thanks

**Comment by devtrends** [comment]
Yep. Will sort it out.

**Comment by devtrends** [comment]
updated and new nuget released.
